export const REQUEST_FILE_UPLOAD = 'REQUEST_FILE_UPLOAD';

export const REQUEST_IMAGE_VISUALIZATION = 'REQUEST_IMAGE_VISUALIZATION';
export const RECEIVE_IMAGE_VISUALIZATION = 'RECEIVE_IMAGE_VISUALIZATION';
export const REJECT_IMAGE_VISUALIZATION = 'REJECT_IMAGE_VISUALIZATION';

export const REQUEST_IMAGES = 'REQUEST_IMAGES';
export const RECEIVE_IMAGES = 'RECEIVE_IMAGES';
export const REJECT_IMAGES = 'REJECT_IMAGES';

export const REQUEST_CNN_CLASSES = 'REQUEST_CNN_CLASSES';
export const RECEIVE_CNN_CLASSES = 'RECEIVE_CNN_CLASSES';
export const REJECT_CNN_CLASSES = 'REJECT_CNN_CLASSES';

export const REQUEST_CNN_LAYERS = 'REQUEST_CNN_LAYERS';
export const RECEIVE_CNN_LAYERS = 'RECEIVE_CNN_LAYERS';
export const REJECT_CNN_LAYERS = 'REJECT_CNN_LAYERS';

export const REQUEST_CNN_CLASSIFICATION = 'REQUEST_CNN_CLASSIFICATION';
export const RECEIVE_CNN_CLASSIFICATION = 'RECEIVE_CNN_CLASSIFICATION';
export const REJECT_CNN_CLASSIFICATION = 'REJECT_CNN_CLASSIFICATION';

export const SET_API_URL = 'SET_API_URL';
export const SET_TEXT_FIELD = 'SET_TEXT_FIELD';

export const SELECT_FILE = 'SELECT_FILE';
export const SELECT_CNN_LAYER = 'SELECT_CNN_LAYER';
export const SELECT_CNN_CLASS = 'SELECT_CNN_CLASS';

export const ATTACH_FILE = 'ATTACH_FILE';
export const DETACH_FILE = 'DETACH_FILE'; 